name: deploy-docs

on:
  push:
    branches:
      - main
      - galactic
    paths:
      - mkdocs.yaml
      - "**/*.md"
      - "**/*.svg"
      - "**/*.png"
      - "**/*.jpg"
  pull_request_target:
    types:
      - opened
      - synchronize
      - labeled
  workflow_dispatch:

jobs:
  prevent-no-label-execution:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/prevent-no-label-execution.yaml@v1
    with:
      label: tag:deploy-docs
    # 手動実行のときはジョブをスキップさせず、結果として成功扱い（outputs.run = 'true'）にするか、
    # あるいは以下のように条件分岐します
    if: github.event_name != 'workflow_dispatch'

  deploy-docs:
    needs: prevent-no-label-execution
    # 手動実行のとき、または prevent-no-label-execution が実行されて条件を満たしたとき
    if: always() && (github.event_name == 'workflow_dispatch' || needs.prevent-no-label-execution.result == 'success')
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Deploy docs
        uses: autowarefoundation/autoware-github-actions/deploy-docs@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          mkdocs-requirements-txt: deploy-docs/mkdocs-requirements.txt
          latest: ${{ github.event_name != 'pull_request_target' && github.ref_name == github.event.repository.default_branch }}

      - name: Show installed packages
        run: |
          echo "--- Final package list used for deployment ---"
          pip list
