name: deploy-docs

on:
  push:
    branches:
      - main
      - galactic
    paths:
      - mkdocs.yaml
      - "**/*.md"
      - "**/*.svg"
      - "**/*.png"
      - "**/*.jpg"
  pull_request_target:
    types:
      - opened
      - synchronize
      - labeled
  workflow_dispatch:

jobs:
  prevent-no-label-execution:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/prevent-no-label-execution.yaml@v1
    with:
      label: tag:deploy-docs

  deploy-docs:
    needs: prevent-no-label-execution
    if: ${{ needs.prevent-no-label-execution.outputs.run == 'true' }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v5
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install mkdocs-material mkdocs-awesome-pages-plugin mkdocs-macros-plugin mkdocs-same-dir pymdown-extensions mkdocs-exclude
    - name: Build docs (Not Deploy)
      run: |
        mkdocs build --clean
    - name: Upload built site as artifact
      uses: actions/upload-artifact@v4
      with:
        name: built-docs-html
        path: site/  # mkdocs build で生成されたディレクトリ
